<div id="view-content">
    <?php
    foreach ($this->paginator as $row) {
        $cnt_tbl = new Vaad_DbTable_ContactCodes();
        $type_desc = '';
        $cat = $cnt_tbl->find($row->cnt_type)->current();
        if ($cat)
            $type_desc = $cat->code_desc;

        $email = $row->cnt_email;
        if (!empty($email)) {
            $em = $row->cnt_email;
            $email = "<a href='/send/to/$em'>$em</a>";
        }

        echo "<span class='postit view'>\n";
        $name = $row->cnt_first_name . ' ' . $row->cnt_last_name;
        echo "<a href='/contacts/view/" . $row->id . "'>$name</a><br>";
        echo $type_desc . "<br />";
        echo $row->cnt_phone1 . "<br />";
        echo $row->cnt_phone2 . "<br />";
        echo $email . "<br>";
        echo "</span>\n";
    }
    ?>
    <div class='clear'></div>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?>
</div>
