drop table reminders cascade;
drop table task_codes cascade;
drop table tasks cascade;
drop table ticket_codes cascade;
drop table projects cascade;
drop table posts cascade;
drop table receipts cascade;
drop table taxes cascade;
drop table tags cascade;
drop table registries cascade;
drop table ticket_history cascade;
drop table todo cascade;
drop table trn_cat_codes cascade;
drop table tickets cascade;
drop table sites cascade;
drop table transactions cascade;
drop table appartments cascade;
drop table buildings cascade;
drop table tenants cascade;
drop table accounts cascade;
drop table contact_codes cascade;
drop table incomes cascade;
drop table ads cascade;
drop table ad_cat_codes cascade;
drop table contacts cascade;
drop table app_codes cascade;
drop table bank_codes cascade;
drop table comment_codes cascade;
drop table pay_codes cascade;
drop table poll_codes cascade;
drop table poll_options cascade;
drop table poll_attendents cascade;
drop table post_codes cascade;
drop table comments cascade;
drop table app_taxes cascade;
drop table apt_maintenance cascade;
drop table polls cascade;
drop table post_tags cascade;
drop table forums cascade;
drop sequence ad_cat_codes_seq_id;
drop sequence app_codes_seq_id;
drop sequence bank_code_id_seq;
drop sequence bank_codes_seq_id;
drop sequence comment_codes_seq_id;
drop sequence contact_codes_id_seq;
drop sequence contact_codes_seq_id;
drop sequence pay_codes_id_seqpay_codes_id_seq;
drop sequence pay_codes_seq_id;
drop sequence poll_codes_seq_id;
drop sequence post_codes_seq_id;
drop sequence task_codes_seq_id;
drop sequence ticket_codes_seq_id;
drop sequence trn_cat_codes_seq_id;

