<?php
$idx = 0;
foreach ($this->posts as $row) {
    $idx++;
    ?>

    <?php if ($idx == 1) { ?>
        <div class='post' id="welcome">
            <h2><?php echo $row->title; ?></h2>
            <?php echo $row->content_txt; ?>
        </div>
<hr>
    <?php } ?>

    <?php if ($idx == 2) { ?>
        <div class='post column'>
            <h3><?php echo $row->title; ?></h3>
            <div class="span-9  right"> <?php echo $row->content_txt; ?></div>
        </div>
    <?php } ?>

    <?php if ($idx == 3) { ?>
        <div class='post column last'>
            <h3><?php echo $row->title; ?></h3>
            <div class="span-9  left"> <?php echo $row->content_txt; ?></div>
        </div>
    <?php } ?>

<?php } ?>

