<div id="view-content">
    <?php
    foreach ($this->paginator as $row) {
        $app = $row->tnt_app_num;
        $name = $row->tnt_first_name . ' ' . $row->tnt_last_name . " ( דירה " . $this->getApt($app) . " )";
        echo "<a href='/tenants/view/" . $row->id . "'>$name</a><br>";
        echo $row->tnt_app_phone. ' ' . $row->tnt_email . "<br>";
    }
    ?>
    <?php echo $this->paginationControl($this->paginator, 'Sliding', 'pagination.phtml') ?>
</div>