<?php $this->placeholder('sidebar')->captureStart() ?>
<h4><?php echo $this->mainMenuTitle; ?></h4>
<ul>
    <?php
        $translator = Zend_Form::getDefaultTranslator();
        foreach ($this->menu as $act => $url) {
            $action = $translator->_($act);
            echo "<li><a href='$url'>$action</a>\n";
        }
    ?>
</ul>
<?php if (($this->action == 'index') and (isset($this->searchForm))): ?>
<h4><?php echo $translator->_('Search'); ?></h4>
<ul class="action_search">

    <?php
    echo $this->searchForm;
    ?>
<?php    endif; ?>
</ul>

<?php $this->placeholder('sidebar')->captureEnd() ?>