<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title></title>
        <meta name="description" content="">
        <link rel="stylesheet" href="/css/screen.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="/css/print.css" type="text/css" media="print">    
        <!--[if lt IE 8]><link rel="stylesheet" href="/css/ie.css" type="text/css" media="screen, projection"><![endif]-->

        <link rel="stylesheet" href="/css/vaad.css" type="text/css" media="screen, projection">
        <link rel="stylesheet" href="css/plugins/rtl/screen.css" type="text/css" media="screen, projection">
        <style type="text/css" media="print">img { display:none; }</style>
        <link rel="icon" type="image/ico" href="/favicon.ico">
        <script type="text/javascript" src="/js/jquery-1.7.min.js"></script>
    </head>
    <body>
        <div class='container main-page'>
            <div id="mainmenu" class="span-24 header last">
                <?php echo $this->navigation()->menu(); ?>
            </div>
            <div class="span-24 dashboard">
                <div class="span-6 search left">
                    <form method="post">
                        <input size="15" type="text" placeholder="חיפוש..." />
                    </form>
                </div>
                <div class="span-12 left  page-title">
                    <?php if (isset($this->topPageTitle)) echo $this->topPageTitle; ?>
                </div>
                <div id="logo"><?php echo $this->BldName(); ?></div>
            </div>
            <div class="span-4 sidebar right">
                <?php echo $this->myDetails(); ?>
            </div>
            <div class='main-content span-19  left' > 
                <?php echo $this->layout()->content; ?>
            </div>
            <div class="footer span-24">
                alkjklasjkl
            </div>
        </div>
    </body>
</html>
